### ISSUE TITLE
TypeError: Cannot read property 'feed' of null

### ISSUE THREAD

**Issue by clochix** [cozy-labs/import-from-google#58]
_Context_: No context, the user has deleted the application (but the error log remains, as an eternal testimony of this crash). I guess the user was just trying to import its data from Google and it didn't work, because this issue made the server crash.

_Stack trace_:
<detail>

```
/usr/local/cozy/apps/import-from-google/build/server/utils/import_photos.js:217
    return getTotal(feed.feed.entry, function() {
                        ^

TypeError: Cannot read property 'feed' of null
    at /usr/local/cozy/apps/import-from-google/build/server/utils/import_photos.js:217:25
    at /usr/local/cozy/apps/import-from-google/node_modules/gdata-js/gdata.js:120:7
    at IncomingMessage.<anonymous> (/usr/local/cozy/apps/import-from-google/node_modules/gdata-js/gdata.js:192:13)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
```

</detail>

**Comment by clochix** [comment]
Fixed in #59, closing.
